services:
  - type: web
    name: nsl-kdd-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn arff_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: nsl_kdd_db
          property: connectionString

databases:
  - name: nsl_kdd_db
    plan: free
    databaseName: nsl_kdd
    user: nsl_kdd_user